version: '3.8'
services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - port=3000
      - URL_MONGOOSE=mongodb://db:27017/dbpersonnes
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 30000:27017
    volumes:
      - testdb:/data/db
volumes:
  testdb: