version: '3.8'
services:
  dbmongo: 
    image: mongo
    ports:
      - 30000:27017
    volumes:
      - mydatamongo:/data/db
  myapi:
    build: ./
    ports:
      - 3000:3000
    environment:
      - port=3000
    depends_on:
      - dbmongo
volumes:
  mydatamongo: